
package com.cesi.recive.wcfService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IComposantService", targetNamespace = "http://192.168.1.19")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IComposantService {


    /**
     * 
     * @param message
     * @return
     *     returns com.cesi.recive.wcfService.MSG
     */
    @WebMethod(operationName = "m_service", action = "http://192.168.1.19/IComposantService/m_service")
    @WebResult(name = "m_serviceResult", targetNamespace = "http://192.168.1.19")
    @RequestWrapper(localName = "m_service", targetNamespace = "http://192.168.1.19", className = "com.cesi.recive.wcfService.MService")
    @ResponseWrapper(localName = "m_serviceResponse", targetNamespace = "http://192.168.1.19", className = "com.cesi.recive.wcfService.MServiceResponse")
    public MSG mService(
        @WebParam(name = "message", targetNamespace = "http://192.168.1.19")
        MSG message);

}
